## Project Euler - Problem 2
##
## Each new term in the Fibonacci sequence is generated by
## adding the previous two terms. By starting with 1 and 2,
## the first 10 terms will be:
##
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
## By considering the terms in the Fibonacci sequence whose
## values do not exceed four million, find the sum of the
## even-valued terms.
##
def sum_even_fibo_terms(N):
	n0 = 1
	n1 = 2
	n = n0 + n1
	s = 0

	while (n <= N):
		s += (n * ((n & 1) == 0))

		n0 = n1
		n1 = n
		n  = n0 + n1

	return s

print("[euler002] s=%d" % sum_even_fibo_terms(4 * 1000 * 1000))

